trigger:
- piplinetest
stages:
  - stage: deploy
    displayName: deploy stage
    jobs:
      - deployment: deploy
        displayName: deploying job
        environment:
         name: 'test'
         resourceType: VirtualMachine
        strategy:
         runOnce:
           deploy:
             steps:
              - task: CmdLine@2
                inputs:
                  script: |
                    echo Write your commands here
                    
                    echo Hello world
