trigger:
- piplinetest
stages:
  - stage: Build
    displayName: build stage 
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: Build
        displayName: Build Maven Project
        steps:
         - task: Maven@3
           displayName: 'Maven Package'
           inputs:
            mavenPomFile: 'pom.xml'
         - task: CopyFiles@2
           displayName: 'Copy Files to artifact staging directory'
           inputs:
             SourceFolder: '$(System.DefaultWorkingDirectory)'
             Contents: '**/target/*.?(war|jar)'
             TargetFolder: $(Build.ArtifactStagingDirectory)
         - publish: $(Build.ArtifactStagingDirectory)
           artifact: drop
  - stage: deploy
    displayName: deploy stage
    dependsOn: build
    jobs:
      - deployment: deploy
        displayName: deploying job
        environment:
         name: 'test'
         resourceType: VirtualMachine
        strategy:
         runOnce:
           deploy:
             steps:
               - task: Bash@3
                 inputs:
                   targetType: inline
                   script: ls 